build-job:
  stage: build
  tags:
    - jetson
  script:
    - |
      source /opt/ros/humble/setup.bash
      rosdep update
      cd ./isaac_ros_apriltag
      bloom-generate rosdebian
      fakeroot debian/rules binary
      cd ..
      export DEB_FILE=$(basename $(find . -type f -name "*.deb" | head -n 1))
      echo "Found deb at: $DEB_FILE"
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "$DEB_FILE" \
           "https://git.sidtrz.com/api/v4/projects/${CI_PROJECT_ID}/packages/generic/isaac_ros_apriltag/latest/$DEB_FILE"
  # artifacts:
  #   paths:
  #     - ./*.deb
  #     - ./*.ddeb
