build-job:
  stage: build
  tags:
    - jetson
  script:
    - |
      source /opt/ros/humble/setup.bash
      rosdep update
      cd ./isaac_ros_apriltag
      bloom-generate rosdebian
      fakeroot debian/rules binary
      export DEB_FILE=$(basename $(find . -maxdepth 1 -type f -name "*.deb" | head -n 1))
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "$DEB_FILE" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/isaac-ros-apriltag/${CI_COMMIT_TAG}/$DEB_FILE"
  # artifacts:
  #   paths:
  #     - ./*.deb
  #     - ./*.ddeb
